### PR TITLE
Just added minor features. :)

### PR DESCRIPTION
**Pull request by ghost**
Hello, I'm honestly.

I like making TUI applications. Today I forked eddy and started exploring the codebase when I saw there was no hjkl movement.
And for a Vim user, that is a very important feature. So I added them. I also added an optional way to exit the editor with q. I also moved the codebase to c++17 (just removed ifndef's and wrote \#pragma once) because c++17 is good. Thank you, hope you well.

### CODE REVIEW

**Comment by ghost** [comment]
Well, the pragma once was a bit biased but I moved the functions up because It's cleaner code. I think code is more readable when You have functions bodes (is that how you say it?) are defined in the same order that the functions were declared in the header files. I also think it's more readable when the functions that other functions dependent on are declared first because then when people see `remTabs` They know what the function is doing under the hood without trying to find the declaration of the function later in the file. But you did say that you did not intend for this to be a project people would contribute to. I like this project and I want this editor to be feature rich with syntax highlighting and code completion So I would like to contribute to this. P.S. hope you a good day. bye.

**Comment by ghost** [comment]
God I was delusional

**Comment by j4cobgarby** [comment]
Oh hi, sorry, I completely missed this pull request, I think the hjkl movement is a good idea

**Comment by ghost** [comment]
ahh don't worry. I was just talking about how weird I was back then. and yeah hjkl is probably the best way of navigating a text file (in my opinion).

**Comment by ghost** [comment]
so should I reopen this request?

**Comment by j4cobgarby** [comment]
Yeah, go for it :)

**Pull request closed without merging**
